version: '3.4'

services:
  badbankv2:
    image: badbankv2
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
